/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.rock_paper_scissors;

import java.awt.Color;
import java.awt.Image;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author abhil
 */
public final class Play_Frame extends javax.swing.JFrame {
    
    
    //create borders
    Border gray_border= BorderFactory.createMatteBorder(1, 1, 1, 1, Color.DARK_GRAY);
    Border orange_border= BorderFactory.createMatteBorder(1, 1, 1, 1, Color.ORANGE);
    
    
    //image path
    String rock ="/images/stone1.png";
    String paper = "/images/paper1.png";
    String scissors ="/images/scissors1.png";

    //create an arrayList
    ArrayList<String> list = new ArrayList<>();
    Random random = new Random();
    int your_wins = 0,computer_wins=0;
    String random_selection;
    
    
    
    
    /**
     * Creates new form Play_Frame
     */
    public Play_Frame() {
        initComponents();
        
        //set borders
        jLabel_You.setBorder(gray_border);
        jLabel_Computer.setBorder(gray_border);
        jLabel_Rock.setBorder(gray_border);
        jLabel_Paper.setBorder(gray_border);
        jLabel_Scissors.setBorder(gray_border);
        // display image in jlabels
        displayImage(rock,jLabel_Rock ,110,90);
        displayImage(paper,jLabel_Paper,110,90);
        displayImage(scissors,jLabel_Scissors,110,90);
        
        //add items to the list
        list.add(rock);
        list.add(paper);
        list.add(scissors);
        
        
    }
    
    // create a function to display image in jlabel
    public void displayImage(String imagePath, JLabel label,int width,int height){
      //get the image 
        ImageIcon imgIco = new ImageIcon(getClass().getResource(imagePath));
      //resize the image
      Image img=imgIco.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
      
      //set image into the jLabel
      label.setIcon(new ImageIcon(img));
      
      
    }

    
    //create a function to get the winner
    public void getWinner(String you,String Computer)
    {
     
        if(you.equals(Computer)){
         System.out.println("draw");
        }
        else if(you.equals(rock)){
            if(Computer.equals(scissors)){
                your_wins++;
                jLabel_Your_Wins.setText(String.valueOf(your_wins));
            }
            else{
                computer_wins++;
                jLabel_Computer_Wins.setText(String.valueOf(computer_wins));
            }
            
        }
        
         else if(you.equals(paper)){
            if(Computer.equals(rock)){
                your_wins++;
                jLabel_Your_Wins.setText(String.valueOf(your_wins));
            }
            else{
                computer_wins++;
                jLabel_Computer_Wins.setText(String.valueOf(computer_wins));
            }
            
        }
        
         else if(you.equals(scissors)){
            if(Computer.equals(paper)){
                your_wins++;
                jLabel_Your_Wins.setText(String.valueOf(your_wins));
            }
            else{
                computer_wins++;
                jLabel_Computer_Wins.setText(String.valueOf(computer_wins));
            }
            
        }
    
        // you can stop when you or the computer reach the 3 wins
        if(your_wins==3 || computer_wins==3){
            
            int yes_no = JOptionPane.showConfirmDialog(null, "Play a new partie ","Play Again", JOptionPane.YES_NO_OPTION);
            if(yes_no ==0)
            {
                
            System.out.println("New Partie");
            jLabel_Computer.setIcon(null);
            jLabel_You.setIcon(null);
            your_wins=0;
            computer_wins=0;
            jLabel_Your_Wins.setText(String.valueOf(your_wins));
            jLabel_Computer_Wins.setText(String.valueOf(computer_wins));
                
            }
 
        }
        
    
    }
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_Computer = new javax.swing.JLabel();
        jLabel_You = new javax.swing.JLabel();
        jLabel_Computer_Wins = new javax.swing.JLabel();
        jLabel_Your_Wins = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_Paper = new javax.swing.JLabel();
        jLabel_Scissors = new javax.swing.JLabel();
        jLabel_Rock = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_Computer.setBackground(new java.awt.Color(204, 204, 255));
        jLabel_Computer.setOpaque(true);

        jLabel_You.setBackground(new java.awt.Color(204, 204, 255));
        jLabel_You.setOpaque(true);

        jLabel_Computer_Wins.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jLabel_Computer_Wins.setForeground(new java.awt.Color(255, 0, 51));
        jLabel_Computer_Wins.setText("0");

        jLabel_Your_Wins.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jLabel_Your_Wins.setForeground(new java.awt.Color(0, 204, 0));
        jLabel_Your_Wins.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Your_Wins.setText("0");

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("-");

        jLabel_Paper.setBackground(new java.awt.Color(204, 204, 255));
        jLabel_Paper.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Paper.setOpaque(true);
        jLabel_Paper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_PaperMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_PaperMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_PaperMouseExited(evt);
            }
        });

        jLabel_Scissors.setBackground(new java.awt.Color(204, 204, 255));
        jLabel_Scissors.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Scissors.setOpaque(true);
        jLabel_Scissors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ScissorsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_ScissorsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_ScissorsMouseExited(evt);
            }
        });

        jLabel_Rock.setBackground(new java.awt.Color(204, 204, 255));
        jLabel_Rock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Rock.setOpaque(true);
        jLabel_Rock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_RockMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_RockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_RockMouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("You");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Computer");

        jPanel2.setBackground(new java.awt.Color(255, 102, 255));

        jLabel1.setFont(new java.awt.Font("Vivaldi", 1, 36)); // NOI18N
        jLabel1.setText("Stone Paper & Scissors");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jLabel_Rock, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_Paper, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_Scissors, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_You, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Your_Wins, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_Computer_Wins, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Computer, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(148, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_You, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Computer, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Computer_Wins, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Your_Wins, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(27, 27, 27)))
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Paper, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Scissors, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Rock, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_RockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_RockMouseClicked
        // display rock image
        displayImage(rock,jLabel_You,160,120);
        //make a random seleection
        random_selection=list.get(random.nextInt(list.size()));
         // display image
        displayImage(random_selection,jLabel_Computer,160,120);
        //
        getWinner(rock,random_selection);
    }//GEN-LAST:event_jLabel_RockMouseClicked

    private void jLabel_PaperMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_PaperMouseClicked
         // display paper image
        displayImage(paper,jLabel_You,160,120);
        //make a random seleection
        random_selection=list.get(random.nextInt(list.size()));
         // display image
        displayImage(random_selection,jLabel_Computer,160,120);
        //
        getWinner(paper,random_selection);
    }//GEN-LAST:event_jLabel_PaperMouseClicked

    private void jLabel_ScissorsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ScissorsMouseClicked
         // display Scissor image
        displayImage(scissors,jLabel_You,160,120);
        //make a random seleection
        random_selection=list.get(random.nextInt(list.size()));
         // display image
        displayImage(random_selection,jLabel_Computer,160,120);
        //
        getWinner(scissors,random_selection);
    }//GEN-LAST:event_jLabel_ScissorsMouseClicked

    private void jLabel_RockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_RockMouseEntered
        // change border
        jLabel_Rock.setBorder(orange_border);
    }//GEN-LAST:event_jLabel_RockMouseEntered

    private void jLabel_RockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_RockMouseExited
        // change border
        jLabel_Rock.setBorder(gray_border);
    }//GEN-LAST:event_jLabel_RockMouseExited

    private void jLabel_PaperMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_PaperMouseEntered
       // change border
        jLabel_Paper.setBorder(orange_border);
    }//GEN-LAST:event_jLabel_PaperMouseEntered

    private void jLabel_PaperMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_PaperMouseExited
        // change border
        jLabel_Paper.setBorder(gray_border);
    }//GEN-LAST:event_jLabel_PaperMouseExited

    private void jLabel_ScissorsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ScissorsMouseEntered
        // change border
        jLabel_Scissors.setBorder(orange_border);
    }//GEN-LAST:event_jLabel_ScissorsMouseEntered

    private void jLabel_ScissorsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ScissorsMouseExited
        // change border
        jLabel_Scissors.setBorder(gray_border);
    }//GEN-LAST:event_jLabel_ScissorsMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Play_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Play_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Play_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Play_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Play_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Computer;
    private javax.swing.JLabel jLabel_Computer_Wins;
    private javax.swing.JLabel jLabel_Paper;
    private javax.swing.JLabel jLabel_Rock;
    private javax.swing.JLabel jLabel_Scissors;
    private javax.swing.JLabel jLabel_You;
    private javax.swing.JLabel jLabel_Your_Wins;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
